#host="staging.c0xgyqperrgk.ap-south-1.rds.amazonaws.com"
#user="admin"
#password="Ps02o2S3r7D"
#database="mynzo"
#mongo_host = "mongodb+srv://mynzostreamlit:HSxeL6gUHTayR8pP@mynzo-test-cluster.yzw39wc.mongodb.net/"
#mongo_db = "mynzo_staging"
#fip_url = "https://api.mynzocarbon.com/dev/v2/users/admin-suggested-plans?net_zero_date=2030-12-31&w_uid=insert_user_id&assigned_date=insert_date"
#register_url = "https://dev.mynzocarbon.com/api/v1/register"
#quiz_list_url = "https://dev.mynzocarbon.com/api/v1/workshop/quiz/question-list?w_id=workshop_choice"

host="production-read.c0xgyqperrgk.ap-south-1.rds.amazonaws.com"
user="admin"
password="Ps02o2S3r7D"
database="mynzo"
mongo_host = "mongodb+srv://mynzostreamlit:HSxeL6gUHTayR8pP@mynzo-test-cluster.yzw39wc.mongodb.net/"
mongo_db = "mynzo"
fip_url = "https://api.mynzocarbon.com/api/v2/users/admin-suggested-plans?net_zero_date=2030-12-31&w_uid=insert_user_id&assigned_date=insert_date"
register_url = "https://api.mynzocarbon.com/api/v1/register"
quiz_list_url = "https://api.mynzocarbon.com/api/v1/workshop/quiz/question-list?w_id=workshop_choice"